config/routes.rb
HelpBaseOnline::Application.routes.draw do
  get "contact_form/new"

  get "contact_form/create"

  resources :subscriptions
  resources :invoices
  resources :invoiceitems
  resources :opportunities
  resources :contact_forms
  match "/contact_form/create" => "contact_form#create", :via => :post
  match "/contact_form/new" => "contact_form#new", :via => :post

  get "organizations/new"

  
  get "page/console"
  match "/console" => "page#console"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions
  resources :contacts
  resources :organizations

  get "home/index", :as => "/"
  
 

  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :contactemail, :firstname, :lastname, :notes, :phone, :state, :zip, :organization_ids
  
  has_and_belongs_to_many :organizations
  has_many :invoices
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :organization, :validate => true
  attribute :phone, :validate => true

  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HelpBase Demo Request",
      :to => "david.dewhirst@threetwelvecreative.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :contact_id, :duedate, :notes, :organization_id, :paid, :totalamount

  belongs_to :contact
  belongs_to :organization
end

app/models/invoiceitem.rb
class Invoiceitem < ActiveRecord::Base
  attr_accessible :amount, :description, :invoice_id, :subscription_id
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  attr_accessible :contact_id, :organization_id, :progress, :status
  
  belongs_to :contact
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :companyemail, :fax, :notes, :organizationname, :phone, :state, :zip
  
  has_and_belongs_to_many :contacts
  has_many :invoices
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :enddate, :invoice_id, :startdate
  
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt,:auth_token,:is_admin
  
  attr_accessor :password
  
  before_save :encrypt_password 
  before_create { generate_token(:auth_token) }
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  attr_accessible :password,:password_confirmation
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless params[:txtemail].nil?
      @email = params[:txtemail]
      UserMailer.demo_email(@email).deliver
    end
    
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def console
    unless is_admin_user?
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    else
      respond_to do |format|
        format.html #{render :layout=>"homeLayout"}# console.html.erb
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice=>"Account successfully created"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoiceitems_helper.rb
module InvoiceitemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelpBase Online</title>
  <!--<link rel="stylesheet" type="text/css" media="screen" href="/assets/style.css">-->
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <meta name="description" content="Cloud-based service provider I & R directory software.">
  <%= csrf_meta_tags %>
  <script type="text/javascript" language="JavaScript">
  function senddemoreq(){
    var xmlHttp = getXMLHTTP();
    var fname = document.getElementById("contactform_name").value;
    if(fname == ""){
      alert("Name is a required field.");
      return;
    }
    var strEmail = document.getElementById("contactform_email").value;
    if(strEmail == ""){
      alert("Email is a required field.");
      return;
    }
    if(!validEmail(strEmail))
    {
      alert("Please enter a valid email address.");
      return;
    }
    var txtCompanyName = document.getElementById("contactform_organization").value;
    if(txtCompanyName == ""){
      alert("Organization is a required field.");
      return;
    }
    var txtPhone = document.getElementById("contactform_phone").value;
    if(txtPhone == ""){
      alert("Phone is a required field.");
      return;
    }
    var strSendMe = "contactform[name]="+fname+"&contactform[email]="+strEmail+"&contactform[phone]="+txtPhone+"&contactform[organization]="+txtCompanyName;
    xmlHttp.open("POST", "/contact_form/create",true);
    xmlHttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
    xmlHttp.send(strSendMe);
    xmlHttp.onreadystatechange = function() {
      if(xmlHttp.readyState === 4) {
        if(xmlHttp.status === 200) {
          //var nextURL = "http://www.google.com";
          //window.location = nextURL;
          var responseContent = xmlHttp.responseText;
          //alert(responseContent);
          var demodiv = document.getElementById("demo");
          demodiv.innerHTML = responseContent;
        } else {
          alert('Error: ' + xmlHttp.status + xmlHttp.responseText);
        }
      } 
      else { //still loading
      }
    };
  }
  function validEmail(email) {
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    if (!filter.test(email)) {
      return false;
    }
    else {return true;}
  }
  function getXMLHTTP() {
    var xmlHttp = null;
    //if XMLHttpRequest is available then creating and returning it
    if( typeof (XMLHttpRequest) != undefined) {
      xmlHttp = new XMLHttpRequest;
      return xmlHttp;
      //if window.ActiveXObject is available than the user is using IE...so we have to create the newest version XMLHttp object
    } else if(window.ActiveXObject) {
      var ieXMLHttpVersions = ['MSXML2.XMLHttp.5.0', 'MSXML2.XMLHttp.4.0', 'MSXML2.XMLHttp.3.0', 'MSXML2.XMLHttp', 'Microsoft.XMLHttp'];
      //In this array we are starting from the first element (newest version) and trying to create it. If there is an
      //exception thrown we are handling it (and doing nothing ^^)
      for(var i = 0; i < ieXMLHttpVersions.length; i++) {
        try {
          xmlHttp = new ActiveXObject(ieXMLHttpVersions[i]);
          return xmlHttp;
        } catch (e) {}
      }
    }
  }
</script>
  <script type="text/javascript">
  	function sendreq()
  	{
  		document.getElementById('demo_form').submit();
  		alert('Thanks! We will be in touch to schedule your HelpBase demo!');
  		return false;
  	}
  </script>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42246819-1', 'helpbasesoftware.com');
  ga('send', 'pageview');

</script>
</head>
<body>
	<% flash.each do |name, msg| %>
    	<%= content_tag :div, msg, :id => "flash#{name}", :style => "position:absolute;z-index:100;" %>
  	<% end %>
  	
<%= yield %>

</body>
</html>

app/views/page/console.html.erb
<h1>Console</h1>


<div><%=link_to "Organizations", organizations_path%></div>
<div><%=link_to "Contacts", contacts_path%></div>
<div><%=link_to "Opportunities", opportunities_path%></div>
<div><%=link_to "Invoices", invoices_path%></div>
<div><%=link_to "Subscriptions", subscriptions_path%></div>