config/routes.rb
HelpBaseOnline::Application.routes.draw do
  get "contact_form/new"

  get "contact_form/create"

  resources :subscriptions
  resources :invoices
  resources :invoiceitems
  resources :opportunities
  resources :contact_forms
  match "/contact_form/create" => "contact_form#create", :via => :post
  match "/contact_form/new" => "contact_form#new", :via => :post

  get "organizations/new"

  
  get "page/console"
  match "/console" => "page#console"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions
  resources :contacts
  resources :organizations

  get "home/index", :as => "/"
  
 

  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :contactemail, :firstname, :lastname, :notes, :phone, :state, :zip, :organization_ids
  
  has_and_belongs_to_many :organizations
  has_many :invoices
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :organization, :validate => true
  attribute :phone, :validate => true

  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HelpBase Demo Request",
      :to => "david.dewhirst@threetwelvecreative.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :contact_id, :duedate, :notes, :organization_id, :paid, :totalamount

  belongs_to :contact
  belongs_to :organization
end

app/models/invoiceitem.rb
class Invoiceitem < ActiveRecord::Base
  attr_accessible :amount, :description, :invoice_id, :subscription_id
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  attr_accessible :contact_id, :organization_id, :progress, :status
  
  belongs_to :contact
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :companyemail, :fax, :notes, :organizationname, :phone, :state, :zip
  
  has_and_belongs_to_many :contacts
  has_many :invoices
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :enddate, :invoice_id, :startdate
  
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt,:auth_token,:is_admin
  
  attr_accessor :password
  
  before_save :encrypt_password 
  before_create { generate_token(:auth_token) }
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  attr_accessible :password,:password_confirmation
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless params[:txtemail].nil?
      @email = params[:txtemail]
      UserMailer.demo_email(@email).deliver
    end
    
  end
  
end

app/controllers/invoiceitems_controller.rb
class InvoiceitemsController < ApplicationController
  # GET /invoiceitems
  # GET /invoiceitems.json
  def index
    @invoiceitems = Invoiceitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoiceitems }
    end
  end

  # GET /invoiceitems/1
  # GET /invoiceitems/1.json
  def show
    @invoiceitem = Invoiceitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoiceitem }
    end
  end

  # GET /invoiceitems/new
  # GET /invoiceitems/new.json
  def new
    @invoiceitem = Invoiceitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoiceitem }
    end
  end

  # GET /invoiceitems/1/edit
  def edit
    @invoiceitem = Invoiceitem.find(params[:id])
  end

  # POST /invoiceitems
  # POST /invoiceitems.json
  def create
    @invoiceitem = Invoiceitem.new(params[:invoiceitem])

    respond_to do |format|
      if @invoiceitem.save
        format.html { redirect_to @invoiceitem, notice: 'Invoiceitem was successfully created.' }
        format.json { render json: @invoiceitem, status: :created, location: @invoiceitem }
      else
        format.html { render action: "new" }
        format.json { render json: @invoiceitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoiceitems/1
  # PUT /invoiceitems/1.json
  def update
    @invoiceitem = Invoiceitem.find(params[:id])

    respond_to do |format|
      if @invoiceitem.update_attributes(params[:invoiceitem])
        format.html { redirect_to @invoiceitem, notice: 'Invoiceitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoiceitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoiceitems/1
  # DELETE /invoiceitems/1.json
  def destroy
    @invoiceitem = Invoiceitem.find(params[:id])
    @invoiceitem.destroy

    respond_to do |format|
      format.html { redirect_to invoiceitems_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def console
    unless is_admin_user?
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    else
      respond_to do |format|
        format.html #{render :layout=>"homeLayout"}# console.html.erb
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice=>"Account successfully created"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoiceitems_helper.rb
module InvoiceitemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invoiceitems/_form.html.erb
<%= form_for(@invoiceitem) do |f| %>
  <% if @invoiceitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoiceitem.errors.count, "error") %> prohibited this invoiceitem from being saved:</h2>

      <ul>
      <% @invoiceitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_id %><br />
    <%= f.number_field :invoice_id %>
  </div>
  <div class="field">
    <%= f.label :subscription_id %><br />
    <%= f.number_field :subscription_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoiceitems/edit.html.erb
<h1>Editing invoiceitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoiceitem %> |
<%= link_to 'Back', invoiceitems_path %>

app/views/invoiceitems/index.html.erb
<h1>Listing invoiceitems</h1>

<table>
  <tr>
    <th>Invoice</th>
    <th>Subscription</th>
    <th>Description</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoiceitems.each do |invoiceitem| %>
  <tr>
    <td><%= invoiceitem.invoice_id %></td>
    <td><%= invoiceitem.subscription_id %></td>
    <td><%= invoiceitem.description %></td>
    <td><%= invoiceitem.amount %></td>
    <td><%= link_to 'Show', invoiceitem %></td>
    <td><%= link_to 'Edit', edit_invoiceitem_path(invoiceitem) %></td>
    <td><%= link_to 'Destroy', invoiceitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoiceitem', new_invoiceitem_path %>

app/views/invoiceitems/new.html.erb
<h1>New invoiceitem</h1>

<%= render 'form' %>

<%= link_to 'Back', invoiceitems_path %>

app/views/invoiceitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invoice:</b>
  <%= @invoiceitem.invoice_id %>
</p>

<p>
  <b>Subscription:</b>
  <%= @invoiceitem.subscription_id %>
</p>

<p>
  <b>Description:</b>
  <%= @invoiceitem.description %>
</p>

<p>
  <b>Amount:</b>
  <%= @invoiceitem.amount %>
</p>


<%= link_to 'Edit', edit_invoiceitem_path(@invoiceitem) %> |
<%= link_to 'Back', invoiceitems_path %>