config/routes.rb
HelpBaseOnline::Application.routes.draw do
  get "contact_form/new"

  get "contact_form/create"

  resources :subscriptions
  resources :invoices
  resources :invoiceitems
  resources :opportunities
  resources :contact_forms
  match "/contact_form/create" => "contact_form#create", :via => :post
  match "/contact_form/new" => "contact_form#new", :via => :post

  get "organizations/new"

  
  get "page/console"
  match "/console" => "page#console"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions
  resources :contacts
  resources :organizations

  get "home/index", :as => "/"
  
 

  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :contactemail, :firstname, :lastname, :notes, :phone, :state, :zip, :organization_ids
  
  has_and_belongs_to_many :organizations
  has_many :invoices
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :organization, :validate => true
  attribute :phone, :validate => true

  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HelpBase Demo Request",
      :to => "david.dewhirst@threetwelvecreative.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :contact_id, :duedate, :notes, :organization_id, :paid, :totalamount

  belongs_to :contact
  belongs_to :organization
end

app/models/invoiceitem.rb
class Invoiceitem < ActiveRecord::Base
  attr_accessible :amount, :description, :invoice_id, :subscription_id
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  attr_accessible :contact_id, :organization_id, :progress, :status
  
  belongs_to :contact
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :companyemail, :fax, :notes, :organizationname, :phone, :state, :zip
  
  has_and_belongs_to_many :contacts
  has_many :invoices
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :enddate, :invoice_id, :startdate
  
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt,:auth_token,:is_admin
  
  attr_accessor :password
  
  before_save :encrypt_password 
  before_create { generate_token(:auth_token) }
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  attr_accessible :password,:password_confirmation
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless params[:txtemail].nil?
      @email = params[:txtemail]
      UserMailer.demo_email(@email).deliver
    end
    
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def console
    unless is_admin_user?
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    else
      respond_to do |format|
        format.html #{render :layout=>"homeLayout"}# console.html.erb
      end
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice=>"Account successfully created"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoiceitems_helper.rb
module InvoiceitemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_id %><br />
    <%= f.number_field :invoice_id %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th>Invoice</th>
    <th>Enddate</th>
    <th>Startdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= subscription.invoice_id %></td>
    <td><%= subscription.enddate %></td>
    <td><%= subscription.startdate %></td>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invoice:</b>
  <%= @subscription.invoice_id %>
</p>

<p>
  <b>Enddate:</b>
  <%= @subscription.enddate %>
</p>

<p>
  <b>Startdate:</b>
  <%= @subscription.startdate %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>