config/routes.rb
HelpBaseOnline::Application.routes.draw do
  get "contact_form/new"

  get "contact_form/create"

  resources :subscriptions
  resources :invoices
  resources :invoiceitems
  resources :opportunities
  resources :contact_forms
  match "/contact_form/create" => "contact_form#create", :via => :post
  match "/contact_form/new" => "contact_form#new", :via => :post

  get "organizations/new"

  
  get "page/console"
  match "/console" => "page#console"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions
  resources :contacts
  resources :organizations

  get "home/index", :as => "/"
  
 

  root :to => "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :contactemail, :firstname, :lastname, :notes, :phone, :state, :zip, :organization_ids
  
  has_and_belongs_to_many :organizations
  has_many :invoices
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :organization, :validate => true
  attribute :phone, :validate => true

  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "HelpBase Demo Request",
      :to => "david.dewhirst@threetwelvecreative.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :contact_id, :duedate, :notes, :organization_id, :paid, :totalamount

  belongs_to :contact
  belongs_to :organization
end

app/models/invoiceitem.rb
class Invoiceitem < ActiveRecord::Base
  attr_accessible :amount, :description, :invoice_id, :subscription_id
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  attr_accessible :contact_id, :organization_id, :progress, :status
  
  belongs_to :contact
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :companyemail, :fax, :notes, :organizationname, :phone, :state, :zip
  
  has_and_belongs_to_many :contacts
  has_many :invoices
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :enddate, :invoice_id, :startdate
  
  belongs_to :invoice
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt,:auth_token,:is_admin
  
  attr_accessor :password
  
  before_save :encrypt_password 
  before_create { generate_token(:auth_token) }
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  attr_accessible :password,:password_confirmation
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless params[:txtemail].nil?
      @email = params[:txtemail]
      UserMailer.demo_email(@email).deliver
    end
    
  end
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def console
    unless is_admin_user?
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    else
      respond_to do |format|
        format.html #{render :layout=>"homeLayout"}# console.html.erb
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice=>"Account successfully created"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoiceitems_helper.rb
module InvoiceitemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organizationname %><br />
    <%= f.text_field :organizationname %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :companyemail %><br />
    <%= f.text_field :companyemail %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing Organizations</h1>

<table>
  <tr>
    <th>Organization Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.organizationname %></td>
    <td><%= organization.companyemail %></td>
    <td><%= organization.phone %></td>
    <td><%= link_to 'Show', organization %></td>
    <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Organization:</b>
  <%= @organization.organizationname %>
</p>

<p>
  <b>Phone:</b>
  <%= @organization.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @organization.companyemail %>
</p>

<p>
  <b>Address:</b>
  <%= @organization.address %>
</p>

<p>
  <b>City:</b>
  <%= @organization.city %>
</p>

<p>
	<b>Contact:</b>
	<%= @organization.contacts.first.firstname if @organization.contacts.first%>
</p>
<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>